<?xml version="1.0" encoding="utf-8"?><Database Name="CompanyManagerDB" Class="LinqToSqlDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-BQJ5871\COMPANYMNGSQL;Initial Catalog=CompanyManagerDB;Persist Security Info=True;User ID=sa" SettingsObjectName="CompanyManager.Properties.Settings" SettingsPropertyName="CompanyManagerDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nif" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MobileContact" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreditLimit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentConditions" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>